/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CrashNative */

#ifndef _Included_CrashNative
#define _Included_CrashNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CrashNative
 * Method:    causeSegmentationFault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CrashNative_causeSegmentationFault
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
