/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CrashDemo */

#ifndef _Included_CrashDemo
#define _Included_CrashDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CrashDemo
 * Method:    causeSegmentationFault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CrashDemo_causeSegmentationFault
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
